stages:
  - neddoc
  - doc
  - deploy
  - test

variables:
  # Tell 'docker:dind' to enable TLS (recommended)
  # and generate certificates in the specified directory.
  DOCKER_TLS_CERTDIR: "/certs"

.link_repos:
  before_script:
    - echo "Linking INET"
    - git clone --depth=1 https://github.com/DETERMINISTIC6G/inet-gptp.git ../inet
    - source ../inet/setenv
    - echo "Getting Data"
    - wget https://github.com/DETERMINISTIC6G/deterministic6g_data/releases/latest/download/histograms_for_omnetpp.zip
    - unzip -o histograms_for_omnetpp.zip -d ../deterministic6g_data
    - rm histograms_for_omnetpp.zip
  after_script:
    - echo "Unlinking Data"
    - rm -rf ../deterministic6g_data
    - echo "Unlinking INET"
    - rm -rf ../inet

neddoc:
  needs: []
  extends:
    - .link_repos
  only:
    - develop
    - documentation
  stage: neddoc
  before_script:
    - !reference [".link_repos", "before_script"]
    - rm -rf public/neddoc
    - rm -rf public/doxy
  script:
    - source ~/omnetpp-6.1/setenv # Needed because opp_neddoc is broken in version 6.2.0
    - xvfb-run -a make neddoc
    - mkdir -p public/doc
    - mv doc/neddoc public/doc/neddoc
    - mv doc/doxy public/doc/doxy
  artifacts:
    paths:
      - public
  tags:
    - d6g
    - shell

doc:
  image: ghcr.io/omnetpp/docker-sphinx:200610
  only:
    - develop
    - documentation
  stage: doc
  dependencies:
    - neddoc
  before_script:
    - mkdir -p doc/neddoc
    - cp public/doc/neddoc/nedtags.xml doc/neddoc
  script:
    - cd doc/src
    - make html
    - cp -r _build/html/* ../../public/doc
  artifacts:
    paths:
      - public
  tags:
    - d6g
    - docker

deploy_ipvs_pages:
  variables:
    DEPLOYMENT_PATH: /mnt/www_d6g/$CI_PROJECT_PATH
  stage: deploy
  dependencies:
    - doc
  environment:
    name: production
    url: "https://ipvs.informatik.uni-stuttgart.de/vs/deterministic6g/$CI_PROJECT_PATH"
  only:
    - develop
    - documentation
  script:
    - rm -rf $DEPLOYMENT_PATH || true
    - mkdir -p $DEPLOYMENT_PATH
    - cp -r public/. $DEPLOYMENT_PATH
  tags:
    - d6g
    - web

fingerprint:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs: []
  extends:
    - .link_repos
  stage: test
  script:
    - source ../inet/setenv
    - cd ../inet
    - make makefiles
    - make -j$(nproc)
    - cd ../6GDetCom_Simulator
    - make makefiles
    - make -j$(nproc)
    - cd tests/fingerprint
    - inet_fingerprinttest
  tags:
    - d6g
    - shell
