[General]
network = Wireless
seed-set = 0
sim-time-limit = 60s
abstract = true
description = "abstract"
num-rngs = 5

# enable time synchronization in all network nodes
*.*.hasTimeSynchronization = true

**.minOscillatorCompensation = -200ppm
**.maxOscillatorCompensation = 200ppm

# all oscillators have a constant drift rate (specified with a random distribution for each one) 
# except for the master clocks, which have a random drift rate
#**.clock.oscillator.typename = "RandomDriftOscillator"
#*.timeTransmitter.clock.oscillator.typename = "RandomDriftOscillator"  
**.clock.oscillator.typename = "RandomDriftOscillator" # use ConstantDriftOscillator for testing in new testing scenario.
**.clock.*.oscillator.typename = "RandomDriftOscillator" # use ConstantDriftOscillator for testing in new testing scenario.
**.oscillator.changeInterval = 12.5ms
**.oscillator.driftRate = uniform(-100ppm, 100ppm)
**.oscillator.driftRateChange = uniform(-0.1ppm, 0.1ppm) # Based on 802.1AS B.1.3.2 (simplified to max error being 5ns/s, needs to be adapted if changeInterval is also adapted)
**.oscillator.driftRateChangeUpperLimit = 100ppm
**.oscillator.driftRateChangeLowerLimit = -100ppm


**.offsetThreshold = 1 us
**.useC5Grr = true

# all Ethernet interfaces have 100 Mbps speed
*.*.eth[*].bitrate = 100Mbps
*.*.*.eth[*].bitrate = 100Mbps

*.visualizer.typename = "IntegratedMultiCanvasVisualizer"
*.visualizer.infoVisualizer[*].displayInfos = true

*.histogramContainer.histograms = {Uplink: "../../../../deterministic6g_data/PD-Wireless-5G-1/s1-UL_wall.xml", Downlink: "../../../../deterministic6g_data/PD-Wireless-5G-1/s10-DL_wall.xml"}

**.sendAnnounceImmediately = true


[Config Task3]
description = "Introduce a Wireless Node"
*.detCom.*tt*.gptp.typename = "DetComGptp"
*.detCom.*tt*.gptp.detComClockModule = "^.detComClock"
**.detComClock.rng-0 = 4
**.detComClock.oscillator.rng-0 = 4

**.nwtt.clock.oscillator.typename = "ConstantDriftOscillator"
**.nwtt.clock.typename = "InstantServoClock"
**.tsnDevice*.clock.typename = "PiServoClock"

*.detCom.nwtt.gptp.gptpNodeType = "MASTER_NODE"
*.detCom.nwtt.gptp.masterPorts = ["eth0", "tt0", "tt1"]
*.detCom.nwtt.gptp.slavePort = ""
*.detCom.dstt[*].gptp.slavePort = "tt0"
*.detCom.dstt[*].gptp.masterPorts = ["eth0"]
*.tsnSwitch*.gptp.slavePort = "eth0"
*.tsnSwitch*.gptp.masterPorts = ["eth1"]
*.tsnDevice*.gptp.slavePort = "eth0"


# Set DetComClock limits
**.detComClock.typename = "OscillatorBasedClock"
**.detComClock.oscillator.typename = "OffsetLimitedRandomDriftOscillator"
**.detComClock.oscillator.changeInterval = 12.5ms
**.detComClock.oscillator.maxDriftRateAdjustment = 0.0009877ppm/4
**.detComClock.oscillator.driftRateChange = uniform(-0.0009877ppm, 0.0009877ppm)
**.detComClock.oscillator.initialDriftRate = 0.0000001ppm
**.detComClock.referenceClock = "detCom.nwtt.detComClock"
**.nwtt.detComClock.initialClockTime = 0s
#**.detComClock.initialClockTime = uniform(-450ns,450ns)

**.detComClock.oscillator.maxOffset = 450ns

# Task 3
# We've now introduced a Logical 5G/TSN bridge with one NW-TT and two DS-TTs.
# Each holds a gPTP and a 5G time, as presented earlier today.
# We've configured the 5G clocks, such that they stay within the time error budget of 900ns.
# Your task:
# - Run the simulation
# - Explore the Task3 graph in the .anf file how the gPTP clocks affect the 5G clocks.

[Config Task4]
sim-time-limit = 120s
description = "Link Failure"
extends = Task3

**.detComClock.initialClockTime = 0s
**.detComClock.oscillator.driftRateChange = 0ppm
**.detComClock.oscillator.maxOffset = 0ns

*.scenarioManagerLink.script = xmldoc("link_failure.xml")

# Task 4
# For this task, we assume idealized 5G clocks. This allows us to properly see the behavior of the gPTP system.
# In the file link_failure.xml, we've already added a link failure, that disables the link dstt[0] <-> nwtt at t=20s.
# a) Extend the scenario:
# - The link between dstt[1] and nwtt breaks at 40s
# - All links are re-established at t=60s
# b) Results:
# - Run the simulation
# - Explore Task4 in the .anf file, what do you discover?
# c) Imagine tsnDeviceB and tsnSwitchB1 are part of one mobile device.
# - Can this subnetwork still operate?
# - What concepts of the first session can we use to allow the independent oparation of this part of the network?


[Config Task5]
extends = Task4
description = "BTCA"

**.resetClockStateOnSyncLoss = true

*.detCom.nwtt.detComClock.oscillator.rng-0 = 1
*.tsnDeviceA.clock.oscillator.rng-0 = 2
*.tsnDeviceB.clock.oscillator.rng-0 = 3

**.gptp.gptpNodeType = "BMCA_NODE"
**.gptp.slavePort = ""
**.gptp.masterPorts = []

*.detCom.*.gptp.bmcaPorts = ["eth0", "tt0", "tt1"]
*.tsnDevice*.gptp.bmcaPorts = ["eth0"]
*.tsnSwitch*.gptp.bmcaPorts = ["eth0", "eth1"]

# Task 4:
# We now want to configure BTCA in our network.
# For our scenario we want to manually define the fallbacks using the grandmasterPriority1 parameter.
# a) Configure the grandmasterPriority1 such that:
# 	- If the network functions normally, the nwtt is chosen.
# 	- In case of a network failure, the tsnDevice nodes should have priority over the tsnSwitch devices when selecting a new grandmaster:

# TODO: Remove sol
*.detCom.nwtt.gptp.grandmasterPriority1 = 1
*.tsnDeviceA.gptp.grandmasterPriority1 = 2
*.tsnDeviceB.gptp.grandmasterPriority1 = 3
*.tsnDeviceC.gptp.grandmasterPriority1 = 4
**.grandmasterPriority1 = 200


# b) Explore the simulation:
#	- Quick run until the failure.
#	- Slow run to see the selection of the new GM.

# c) Explore the "Task 5" and "Task 5 (zoomed 20s)" graphs in the .anf file.
#	- What do you discover at around 20s and 40s where the failures occur?

[Config Task6]
extends = Task4
description = "Hot Standby"

# In the following we've now confiured a HotStandy Domain.
# For Domain 1, tsnDeviceA is the HotStandy Grandmaster.
# Task 6:
#	- Run the simulation.
#	- Compare the results of Task 6 to the ones of Task 5.


*.detCom.nwtt.detComClock.oscillator.rng-0 = 1
*.tsnDeviceA.clock.clock[0].oscillator.rng-0 = 2
*.tsnDeviceB.clock.clock[0].oscillator.rng-0 = 3

**.gptp.typename = "MultiDomainGptp"
**.gptp.numDomains = 2

*.tsnDevice*.clock.typename = "MultiClock"
*.detCom.dstt[*].clock.typename = "MultiClock"
*.detCom.nwtt.clock.typename = "MultiClock"
*.tsnSwitch*.clock.typename = "MultiClock"

*.detCom.nwtt.clock.clock[0].oscillator.initialDriftRate = 0ppm # According to 802.1AS B.1.1

*.detCom.*tt*.gptp.domain[*].typename = "DetComGptp"
*.detCom.*tt*.gptp.domain[*].detComClockModule = "^.^.detComClock"

# tsnDeviceA clock 0 is slave to nwtt, master for domain 1
# tsnDeviceA clock 1 is fallback on domain 2
*.tsnDeviceA.clock.numClocks = 1
*.tsnDeviceA.gptp.domain[0..1].clockModule = "^.^.clock.clock[0]"

# tsnDeviceB clock 0 is slave to nwtt, clock 1 to tsnDevice A
# activeIndex is master to domain 2
*.tsnDeviceB.clock.numClocks = 1
*.tsnDeviceB.gptp.domain[0..1].clockModule = "^.^.clock.clock[0]"

**.clock.numClocks = 2

*.tsnDeviceA.gptp.hasHotStandby = false
*.tsnDeviceB.gptp.hasHotStandby = false


# Domain 0 (nwtt master)
#**.gptp.domain[0].syncInitialOffset = 30s
#**.gptp.domain[0].pdelayInitialOffset = 30s
*.detCom.nwtt.gptp.domain[0].gptpNodeType = "MASTER_NODE"
*.detCom.nwtt.gptp.domain[0].masterPorts = ["eth0", "tt0", "tt1"]
*.detCom.dstt[*].gptp.domain[0].slavePort = "tt0"
*.detCom.dstt[*].gptp.domain[0].masterPorts = ["eth0"]
*.tsnSwitch*.gptp.domain[0].slavePort = "eth0"
*.tsnSwitch*.gptp.domain[0].masterPorts = ["eth1"]
*.tsnDevice*.gptp.domain[0].slavePort = "eth0"
**.domain[0].syncInitialOffset = syncInterval * 1 / 2


# Domain 1 (tsnDeviceA master, right side)
#**.gptp.domain[1].syncInitialOffset = 30s
#**.gptp.domain[1].pdelayInitialOffset = 30s
**.domain[1].syncInitialOffset = syncInterval * 2 / 2

*.tsnDeviceA.gptp.domain[1].gptpNodeType = "MASTER_NODE"
*.tsnDeviceA.gptp.domain[1].masterPorts = ["eth0"]
*.tsnDeviceA.gptp.domain[1].slavePort = ""
*.tsnSwitchA*.gptp.domain[1].slavePort = "eth1"
*.tsnSwitchA*.gptp.domain[1].masterPorts = ["eth0"]
*.detCom.nwtt.gptp.domain[1].slavePort = "eth0"
*.detCom.nwtt.gptp.domain[1].gptpNodeType = "SLAVE_NODE"

# Domain 2 (tsnDeviceB master, right side)
*.tsn*B*.gptp.domain[1].domainNumber = 2
**.dstt[*].gptp.domain[1].domainNumber = 2
*.tsnDeviceC.gptp.domain[1].domainNumber = 2


*.tsnDeviceB.gptp.domain[1].gptpNodeType = "MASTER_NODE"
*.tsnDeviceB.gptp.domain[1].masterPorts = ["eth0"]
*.tsnDeviceB.gptp.domain[1].slavePort = ""
*.tsnSwitchB*.gptp.domain[1].slavePort = "eth1"
*.tsnSwitchB*.gptp.domain[1].masterPorts = ["eth0"]
*.detCom.dstt[0].gptp.domain[1].slavePort = "eth0"
*.detCom.dstt[0].gptp.domain[1].masterPorts = ["tt1"]
*.detCom.dstt[1].gptp.domain[1].slavePort = "tt1"
*.detCom.dstt[1].gptp.domain[1].masterPorts = ["eth0"]
*.tsnDeviceC.gptp.domain[1].slavePort = "eth0"

# Set all reference clocks to master clock so the time difference can be visualized
**.clock*.referenceClock = "detCom.nwtt.detComClock"


